name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '20'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: gradle build
